'use client';

import { useEffect, useState } from 'react';
import { 
  TrendingUp, Calendar, Users, Clock, Download, 
  BarChart3, PieChart, Activity, AlertCircle, 
  RefreshCw, Filter, Trophy, Target, Zap, 
  MapPin, History, FileText, Database, Printer,
  CheckCircle2, XCircle, AlertTriangle
} from 'lucide-react';
import pb from '@/lib/pocketbase';

// ─── Sub-Component: Report History Table ───
function ReportHistoryTable({ data }: { data: any[] }) {
  const formatDate = (dateStr: string) => {
    if (!dateStr || dateStr === 'N/A') return 'N/A';
    return new Date(dateStr).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  };

  const getFormatBadge = (format: string) => {
    const f = format?.toUpperCase();
    if (f === 'PDF') return 'bg-red-50 text-red-700 ring-red-600/20';
    if (f === 'EXCEL' || f === 'CSV') return 'bg-emerald-50 text-emerald-700 ring-emerald-600/20';
    return 'bg-slate-100 text-slate-700 ring-slate-600/20';
  };

  const getReportTypeIcon = (reportType: string) => {
    const type = reportType?.toLowerCase() || '';
    if (type.includes('performance')) return <TrendingUp className="w-3.5 h-3.5 text-blue-500" />;
    if (type.includes('meeting')) return <Calendar className="w-3.5 h-3.5 text-purple-500" />;
    if (type.includes('directory') || type.includes('officer')) return <Users className="w-3.5 h-3.5 text-emerald-500" />;
    return <FileText className="w-3.5 h-3.5 text-slate-400" />;
  };

  if (data.length === 0) {
    return (
      <div className="px-6 py-16 text-center">
        <div className="w-14 h-14 mx-auto mb-3 rounded-2xl bg-slate-50 flex items-center justify-center">
          <FileText className="w-6 h-6 text-slate-300" strokeWidth={1.5} />
        </div>
        <p className="text-[14px] font-semibold text-slate-600">No reports generated yet</p>
        <p className="text-[12px] text-slate-400 mt-1">Generated reports will appear here</p>
      </div>
    );
  }

  return (
    <div className="overflow-x-auto">
      <table className="w-full">
        <thead>
          <tr className="border-b border-slate-100 bg-slate-50/50">
            <th className="px-6 py-3 text-left text-[11px] font-semibold text-slate-400 uppercase tracking-wider">Generated</th>
            <th className="px-4 py-3 text-left text-[11px] font-semibold text-slate-400 uppercase tracking-wider">Report Title</th>
            <th className="px-4 py-3 text-left text-[11px] font-semibold text-slate-400 uppercase tracking-wider">Type</th>
            <th className="px-4 py-3 text-left text-[11px] font-semibold text-slate-400 uppercase tracking-wider">Date Range</th>
            <th className="px-4 py-3 text-left text-[11px] font-semibold text-slate-400 uppercase tracking-wider">Department</th>
            <th className="px-4 py-3 text-left text-[11px] font-semibold text-slate-400 uppercase tracking-wider">Officer Type</th>
            <th className="px-4 py-3 text-left text-[11px] font-semibold text-slate-400 uppercase tracking-wider">Format</th>
            <th className="px-4 py-3 text-left text-[11px] font-semibold text-slate-400 uppercase tracking-wider">Generated By</th>
            <th className="px-4 py-3 text-left text-[11px] font-semibold text-slate-400 uppercase tracking-wider">Status</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-slate-50">
          {data.map((log: any) => {
            const statusColor = log.status?.toLowerCase().includes('fail') || log.status?.toLowerCase().includes('error')
              ? 'bg-red-50 text-red-700 ring-red-600/20'
              : log.status?.toLowerCase().includes('pending') || log.status?.toLowerCase().includes('processing')
              ? 'bg-amber-50 text-amber-700 ring-amber-600/20'
              : 'bg-emerald-50 text-emerald-700 ring-emerald-600/20';

            return (
              <tr key={log.id} className="group hover:bg-slate-50/60 transition-colors">
                <td className="px-6 py-4 text-[12px] text-slate-500 font-medium whitespace-nowrap">
                  {log.created ? new Date(log.created).toLocaleString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }) : '-'}
                </td>
                <td className="px-4 py-4">
                  <div className="flex items-center gap-2">
                    {getReportTypeIcon(log.report_type)}
                    <span className="text-[13px] font-semibold text-slate-800">{log.title || 'Untitled Report'}</span>
                  </div>
                </td>
                <td className="px-4 py-4">
                  <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-[11px] font-semibold bg-blue-50 text-blue-700 ring-1 ring-inset ring-blue-600/20">
                    {getReportTypeIcon(log.report_type)}
                    {log.report_type || 'Report'}
                  </span>
                </td>
                <td className="px-4 py-4 text-[12px] text-slate-600">
                  <div className="flex flex-col gap-0.5">
                    <span className="text-slate-600">{formatDate(log.date_from)}</span>
                    {log.date_to && log.date_to !== 'N/A' && (
                      <span className="text-slate-400 text-[11px]">to {formatDate(log.date_to)}</span>
                    )}
                  </div>
                </td>
                <td className="px-4 py-4 text-[13px] text-slate-600">
                  {log.department && log.department !== 'N/A' ? log.department : '-'}
                </td>
                <td className="px-4 py-4">
                  {log.officer_type ? (
                    <span className={`inline-flex items-center px-2 py-0.5 rounded text-[11px] font-medium ${
                      log.officer_type === 'IAS' ? 'bg-indigo-50 text-indigo-700' :
                      log.officer_type === 'IPS' ? 'bg-slate-700 text-white' :
                      log.officer_type.toLowerCase() === 'both' ? 'bg-purple-50 text-purple-700' :
                      'bg-gray-100 text-gray-600'
                    }`}>
                      {log.officer_type}
                    </span>
                  ) : '-'}
                </td>
                <td className="px-4 py-4">
                  {log.format ? (
                    <span className={`inline-flex items-center gap-1 px-2.5 py-1 rounded-lg text-[11px] font-semibold ring-1 ring-inset ${getFormatBadge(log.format)}`}>
                      {log.format.toUpperCase() === 'PDF' ? <Printer className="w-3 h-3" /> : <FileText className="w-3 h-3" />}
                      {log.format.toUpperCase()}
                    </span>
                  ) : '-'}
                </td>
                <td className="px-4 py-4">
                  <div className="flex items-center gap-2">
                    <div className="w-6 h-6 rounded-full bg-gradient-to-br from-blue-500 to-indigo-600 flex items-center justify-center text-white text-[10px] font-bold flex-shrink-0">
                      {(log.generated_by || 'S').charAt(0).toUpperCase()}
                    </div>
                    <span className="text-[13px] text-slate-600 font-medium">{log.generated_by || 'System'}</span>
                  </div>
                </td>
                <td className="px-4 py-4">
                  <span className={`inline-flex items-center px-2.5 py-1 text-[11px] font-semibold rounded-lg ring-1 ring-inset ${statusColor}`}>
                    {log.status || 'Generated'}
                  </span>
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

// ─── Sub-Component: Update Logs Table ───
function UpdateLogsTable({ data }: { data: any[] }) {
  const getLogIcon = (action: string) => {
    const a = action?.toLowerCase() || '';
    if (a.includes('update') || a.includes('sync')) return <RefreshCw className="w-3.5 h-3.5 text-amber-500" />;
    if (a.includes('delete') || a.includes('remove')) return <XCircle className="w-3.5 h-3.5 text-red-500" />;
    if (a.includes('create') || a.includes('add')) return <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" />;
    return <Activity className="w-3.5 h-3.5 text-slate-400" />;
  };

  const getStatusColor = (status: string) => {
    const s = (status || 'Success').toLowerCase();
    if (s.includes('fail') || s.includes('error')) return 'bg-red-50 text-red-700 ring-red-600/20';
    if (s.includes('pending') || s.includes('processing')) return 'bg-amber-50 text-amber-700 ring-amber-600/20';
    return 'bg-emerald-50 text-emerald-700 ring-emerald-600/20';
  };

  if (data.length === 0) {
    return (
      <div className="px-6 py-16 text-center">
        <div className="w-14 h-14 mx-auto mb-3 rounded-2xl bg-slate-50 flex items-center justify-center">
          <Database className="w-6 h-6 text-slate-300" strokeWidth={1.5} />
        </div>
        <p className="text-[14px] font-semibold text-slate-600">No update logs found</p>
        <p className="text-[12px] text-slate-400 mt-1">System update activities will appear here</p>
      </div>
    );
  }

  return (
    <div className="overflow-x-auto">
      <table className="w-full">
        <thead>
          <tr className="border-b border-slate-100 bg-slate-50/50">
            <th className="px-6 py-3 text-left text-[11px] font-semibold text-slate-400 uppercase tracking-wider">Timestamp</th>
            <th className="px-4 py-3 text-left text-[11px] font-semibold text-slate-400 uppercase tracking-wider">Action / Event</th>
            <th className="px-4 py-3 text-left text-[11px] font-semibold text-slate-400 uppercase tracking-wider">User</th>
            <th className="px-4 py-3 text-left text-[11px] font-semibold text-slate-400 uppercase tracking-wider">Details</th>
            <th className="px-4 py-3 text-left text-[11px] font-semibold text-slate-400 uppercase tracking-wider">Status</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-slate-50">
          {data.map((log: any) => {
            const action = log.action || log.event || log.type || log.title || 'System Activity';
            const user = log.user || log.performed_by || log.username || log.author || 'System';
            const details = log.details || log.description || log.message || log.notes || 'No additional details';
            
            return (
              <tr key={log.id} className="group hover:bg-slate-50/60 transition-colors">
                <td className="px-6 py-4 text-[12px] text-slate-500 font-medium whitespace-nowrap">
                  {log.created ? new Date(log.created).toLocaleString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }) : '-'}
                </td>
                <td className="px-4 py-4">
                  <span className="inline-flex items-center gap-1.5 text-[13px] font-semibold text-slate-800">
                    {getLogIcon(action)}
                    {action}
                  </span>
                </td>
                <td className="px-4 py-4">
                  <div className="flex items-center gap-2">
                    <div className="w-6 h-6 rounded-full bg-slate-100 flex items-center justify-center text-[10px] font-bold text-slate-600 flex-shrink-0">
                      {user.charAt(0).toUpperCase()}
                    </div>
                    <span className="text-[13px] text-slate-600 font-medium">{user}</span>
                  </div>
                </td>
                <td className="px-4 py-4 text-[13px] text-slate-500 max-w-md truncate" title={details}>
                  {details}
                </td>
                <td className="px-4 py-4">
                  <span className={`inline-flex items-center px-2.5 py-1 text-[11px] font-semibold rounded-lg ring-1 ring-inset ${getStatusColor(log.status)}`}>
                    {log.status || 'Success'}
                  </span>
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

// ─── Main Page Component ───
export default function ReportsPage() {
  const [data, setData] = useState<any>(null);
  const [reportHistory, setReportHistory] = useState<any[]>([]);
  const [updateLogs, setUpdateLogs] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [dateRange, setDateRange] = useState('all');
  const [activeLogTab, setActiveLogTab] = useState<'reports' | 'updates'>('reports');

  useEffect(() => {
    loadReportData();
  }, [dateRange]);

  async function loadReportData() {
    try {
      setLoading(true);
      setError('');
      
      const [meetings, iasOfficers, ipsOfficers, reportHistoryRes, updateLogsRes] = await Promise.all([
        pb.collection('meetings').getFullList({ sort: '-meeting_date' }),
        pb.collection('ias_officers').getList(1, 1, {}),
        pb.collection('ips_officers').getList(1, 1, {}),
        pb.collection('report_history').getList(1, 50, { sort: '-created' }).catch(() => ({ items: [] })),
        pb.collection('update_logs').getList(1, 50, { sort: '-created' }).catch(() => ({ items: [] })),
      ]);

      let filteredMeetings = meetings;
      const now = new Date();
      
      if (dateRange === 'week') {
        const weekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
        filteredMeetings = meetings.filter(m => new Date(m.meeting_date || m.created) >= weekAgo);
      } else if (dateRange === 'month') {
        const monthAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
        filteredMeetings = meetings.filter(m => new Date(m.meeting_date || m.created) >= monthAgo);
      } else if (dateRange === 'year') {
        const yearAgo = new Date(now.getTime() - 365 * 24 * 60 * 60 * 1000);
        filteredMeetings = meetings.filter(m => new Date(m.meeting_date || m.created) >= yearAgo);
      }

      const totalMeetings = filteredMeetings.length;
      const completedMeetings = filteredMeetings.filter(m => m.status?.toLowerCase() === 'completed').length;
      const scheduledMeetings = filteredMeetings.filter(m => m.status?.toLowerCase() === 'scheduled').length;
      const cancelledMeetings = filteredMeetings.filter(m => m.status?.toLowerCase() === 'cancelled').length;
      const rescheduledMeetings = filteredMeetings.filter(m => m.status?.toLowerCase() === 'rescheduled').length;
      const rejectedMeetings = filteredMeetings.filter(m => m.status?.toLowerCase() === 'rejected').length;

      const totalDuration = filteredMeetings.reduce((acc: number, m: any) => acc + (parseInt(m.duration) || 0), 0);
      const avgDuration = totalMeetings > 0 ? Math.round(totalDuration / totalMeetings) : 0;
      const completionRate = totalMeetings > 0 ? Math.round((completedMeetings / totalMeetings) * 100) : 0;

      const meetingTypes: Record<string, number> = {};
      filteredMeetings.forEach(m => {
        const type = m.meeting_type || 'Other';
        meetingTypes[type] = (meetingTypes[type] || 0) + 1;
      });

      const officerMeetings: Record<string, { count: number; type: string }> = {};
      filteredMeetings.forEach(m => {
        if (m.officer_name) {
          if (!officerMeetings[m.officer_name]) {
            officerMeetings[m.officer_name] = { count: 0, type: m.officer_type || 'IAS' };
          }
          officerMeetings[m.officer_name].count += 1;
        }
      });
      const topOfficers = Object.entries(officerMeetings)
        .sort(([, a], [, b]) => b.count - a.count)
        .slice(0, 5)
        .map(([name, info]) => ({ name, count: info.count, type: info.type }));

      const dayNames = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
      const dayActivity = Array(7).fill(0);
      filteredMeetings.forEach(m => {
        const date = new Date(m.meeting_date || m.created);
        if (!isNaN(date.getTime())) {
          dayActivity[date.getDay()] += 1;
        }
      });
      const maxDayActivity = Math.max(...dayActivity, 1);

      const monthlyData: { month: string; count: number }[] = [];
      for (let i = 5; i >= 0; i--) {
        const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
        const monthName = d.toLocaleString('default', { month: 'short' });
        const count = filteredMeetings.filter(m => {
          const meetingDate = new Date(m.meeting_date || m.created);
          return meetingDate.getMonth() === d.getMonth() && meetingDate.getFullYear() === d.getFullYear();
        }).length;
        monthlyData.push({ month: monthName, count });
      }

      setData({
        totalMeetings, completedMeetings, scheduledMeetings, cancelledMeetings, 
        rescheduledMeetings, rejectedMeetings,
        iasOfficers: iasOfficers.totalItems, ipsOfficers: ipsOfficers.totalItems,
        totalOfficers: iasOfficers.totalItems + ipsOfficers.totalItems,
        totalDuration, avgDuration, completionRate,
        meetingTypes, topOfficers, dayActivity, dayNames, maxDayActivity, monthlyData
      });
      
      setReportHistory(reportHistoryRes.items || []);
      setUpdateLogs(updateLogsRes.items || []);
    } catch (error: any) {
      console.error('Error fetching report data:', error);
      setError(error.message || 'Failed to load reports. Check PocketBase connection.');
    } finally {
      setLoading(false);
    }
  }

  const handleExport = () => {
    if (!data) return;
    const csvContent = [
      ['Civillist Analytics Report', `Generated: ${new Date().toLocaleString()}`],
      [''],
      ['Key Metrics'],
      ['Total Meetings', data.totalMeetings],
      ['Completed', data.completedMeetings],
      ['Scheduled', data.scheduledMeetings],
      ['Cancelled', data.cancelledMeetings],
      ['Completion Rate', `${data.completionRate}%`],
      ['Avg Duration', `${data.avgDuration} min`],
      [''],
      ['Officer Leaderboard'],
      ['Rank', 'Name', 'Type', 'Meetings'],
      ...data.topOfficers.map((o: any, i: number) => [i + 1, o.name, o.type, o.count]),
    ].map(row => row.join(',')).join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `civillist-report-${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="p-8 flex items-center justify-center min-h-screen bg-slate-50/50">
        <div className="flex flex-col items-center gap-4">
          <div className="w-12 h-12 border-4 border-slate-200 border-t-slate-800 rounded-full animate-spin" />
          <p className="text-slate-600 font-medium">Loading analytics...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-8 max-w-7xl mx-auto min-h-screen flex items-center justify-center">
        <div className="bg-red-50 border border-red-200 rounded-2xl p-8 text-center max-w-md w-full shadow-sm">
          <AlertCircle className="w-12 h-12 text-red-500 mx-auto mb-4" />
          <h2 className="text-lg font-bold text-red-900 mb-2">Failed to Load Reports</h2>
          <p className="text-red-700 mb-6 text-sm">{error}</p>
          <button onClick={loadReportData} className="inline-flex items-center gap-2 px-4 py-2.5 bg-red-600 text-white text-sm font-semibold rounded-xl hover:bg-red-700 transition-colors shadow-sm">
            <RefreshCw className="w-4 h-4" /> Try Again
          </button>
        </div>
      </div>
    );
  }

  if (!data) return null;

  const stats = [
    { label: 'Total Meetings', value: data.totalMeetings, icon: Calendar, color: 'blue', trend: '+12%' },
    { label: 'Completion Rate', value: `${data.completionRate}%`, icon: Target, color: 'emerald', trend: '+8%' },
    { label: 'Total Officers', value: data.totalOfficers, icon: Users, color: 'indigo', trend: '+5%' },
    { label: 'Avg Duration', value: `${data.avgDuration}m`, icon: Clock, color: 'amber', trend: 'Stable' },
  ];

  const colorMap: Record<string, string> = {
    blue: 'bg-blue-50 text-blue-600', 
    emerald: 'bg-emerald-50 text-emerald-600',
    amber: 'bg-amber-50 text-amber-600', 
    indigo: 'bg-indigo-50 text-indigo-600',
  };

  const statusSegments = [
    { label: 'Completed', value: data.completedMeetings, color: '#10b981', bg: 'from-emerald-500 to-emerald-600' },
    { label: 'Scheduled', value: data.scheduledMeetings, color: '#3b82f6', bg: 'from-blue-500 to-blue-600' },
    { label: 'Cancelled', value: data.cancelledMeetings, color: '#ef4444', bg: 'from-red-500 to-red-600' },
    { label: 'Rescheduled', value: data.rescheduledMeetings, color: '#f59e0b', bg: 'from-amber-500 to-amber-600' },
    { label: 'Rejected', value: data.rejectedMeetings, color: '#8b5cf6', bg: 'from-violet-500 to-violet-600' },
  ].filter(s => s.value > 0);
  const totalStatus = statusSegments.reduce((sum, s) => sum + s.value, 0);

  return (
    <div className="min-h-screen bg-[#f8fafc] p-6 lg:p-8 max-w-[1400px] mx-auto space-y-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 tracking-tight">Reports & Analytics</h1>
          <p className="text-slate-500 text-sm mt-1">Comprehensive overview of meetings, officers, and system activity</p>
        </div>
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2 bg-white border border-slate-200 rounded-xl px-3 py-2 shadow-sm">
            <Filter className="w-4 h-4 text-slate-400" />
            <select 
              value={dateRange} 
              onChange={(e) => setDateRange(e.target.value)} 
              className="text-sm font-medium text-slate-700 bg-transparent focus:outline-none cursor-pointer"
            >
              <option value="all">All Time</option>
              <option value="week">Last 7 Days</option>
              <option value="month">Last 30 Days</option>
              <option value="year">Last Year</option>
            </select>
          </div>
          <button 
            onClick={handleExport} 
            className="inline-flex items-center gap-2 px-4 py-2.5 bg-slate-900 hover:bg-slate-800 text-white text-sm font-semibold rounded-xl transition-colors shadow-sm shadow-slate-900/10"
          >
            <Download className="w-4 h-4" /> Export CSV
          </button>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {stats.map((stat) => {
          const Icon = stat.icon;
          return (
            <div key={stat.label} className="bg-white p-5 rounded-2xl border border-slate-200/60 shadow-sm hover:shadow-md hover:-translate-y-0.5 transition-all duration-300">
              <div className="flex items-center justify-between mb-4">
                <div className={`w-10 h-10 rounded-xl flex items-center justify-center ${colorMap[stat.color]}`}>
                  <Icon className="w-5 h-5" strokeWidth={1.75} />
                </div>
                <span className="text-[11px] font-semibold text-emerald-700 bg-emerald-50 px-2 py-1 rounded-lg ring-1 ring-emerald-600/10">
                  {stat.trend}
                </span>
              </div>
              <p className="text-2xl font-extrabold text-slate-900 mb-1 tracking-tight">{stat.value}</p>
              <p className="text-[13px] font-medium text-slate-500">{stat.label}</p>
            </div>
          );
        })}
      </div>

      {/* Charts Row */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Status Distribution */}
        <div className="bg-white rounded-2xl border border-slate-200/60 shadow-sm p-6 hover:shadow-md transition-shadow duration-300">
          <div className="flex items-center gap-2 mb-6">
            <PieChart className="w-5 h-5 text-slate-500" />
            <h3 className="text-[15px] font-bold text-slate-900">Meeting Status</h3>
          </div>
          {totalStatus === 0 ? (
            <div className="flex items-center justify-center h-48 text-slate-400 text-sm">No meetings yet</div>
          ) : (
            <div className="flex items-center gap-8">
              <div className="relative w-32 h-32 flex-shrink-0">
                <svg className="w-full h-full -rotate-90" viewBox="0 0 100 100">
                  {statusSegments.reduce((acc, item, idx) => {
                    const circumference = 2 * Math.PI * 40;
                    const percent = item.value / totalStatus;
                    const rotation = statusSegments.slice(0, idx).reduce((sum, prev) => sum + (prev.value / totalStatus) * 360, 0);
                    acc.push(
                      <circle 
                        key={item.label} 
                        cx="50" cy="50" r="40" 
                        fill="none" 
                        stroke={item.color} 
                        strokeWidth="12"
                        strokeDasharray={`${percent * circumference} ${circumference}`}
                        transform={`rotate(${rotation} 50 50)`} 
                        className="transition-all duration-700 ease-out" 
                      />
                    );
                    return acc;
                  }, [] as JSX.Element[])}
                </svg>
                <div className="absolute inset-0 flex flex-col items-center justify-center">
                  <span className="text-2xl font-extrabold text-slate-900">{totalStatus}</span>
                  <span className="text-[11px] text-slate-400 font-medium">Total</span>
                </div>
              </div>
              <div className="flex-1 space-y-3">
                {statusSegments.map(segment => (
                  <div key={segment.label} className="flex items-center justify-between">
                    <div className="flex items-center gap-2.5">
                      <div className={`w-2.5 h-2.5 rounded-full bg-gradient-to-r ${segment.bg}`} />
                      <span className="text-[13px] font-medium text-slate-600">{segment.label}</span>
                    </div>
                    <span className="text-[13px] font-bold text-slate-900 tabular-nums">
                      {Math.round((segment.value / totalStatus) * 100)}%
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Monthly Trend Bar Chart */}
        <div className="bg-white rounded-2xl border border-slate-200/60 shadow-sm p-6 lg:col-span-2 hover:shadow-md transition-shadow duration-300">
          <div className="flex items-center gap-2 mb-6">
            <BarChart3 className="w-5 h-5 text-slate-500" />
            <h3 className="text-[15px] font-bold text-slate-900">Monthly Meeting Trends</h3>
          </div>
          <div className="flex items-end justify-between gap-3 h-48 pt-2 px-2">
            {data.monthlyData.map((month: { month: string; count: number }, idx: number) => {
              const maxCount = Math.max(...data.monthlyData.map((m: any) => m.count), 1);
              const height = (month.count / maxCount) * 100;
              return (
                <div key={idx} className="flex-1 flex flex-col items-center gap-3 group">
                  <span className="text-[11px] font-semibold text-slate-600 opacity-0 group-hover:opacity-100 transition-opacity">
                    {month.count}
                  </span>
                  <div className="w-full bg-slate-100 rounded-t-xl relative overflow-hidden" style={{ height: '100%' }}>
                    <div 
                      className="absolute bottom-0 w-full bg-gradient-to-t from-slate-800 to-slate-600 rounded-t-xl transition-all duration-700 ease-out group-hover:from-slate-900 group-hover:to-slate-700" 
                      style={{ height: `${Math.max(height, 4)}%` }} 
                    />
                  </div>
                  <span className="text-[11px] text-slate-400 font-medium">{month.month}</span>
                </div>
              );
            })}
          </div>
        </div>
      </div>

      {/* Insights Row */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Officer Leaderboard */}
        <div className="bg-white rounded-2xl border border-slate-200/60 shadow-sm p-6 hover:shadow-md transition-shadow duration-300">
          <div className="flex items-center gap-2 mb-5">
            <Trophy className="w-5 h-5 text-amber-500" />
            <h3 className="text-[15px] font-bold text-slate-900">Top Officers</h3>
          </div>
          {data.topOfficers.length === 0 ? (
            <div className="flex items-center justify-center h-32 text-slate-400 text-sm">No meeting data yet</div>
          ) : (
            <div className="space-y-4">
              {data.topOfficers.map((officer: any, idx: number) => (
                <div key={idx} className="flex items-center gap-3">
                  <div className={`w-8 h-8 rounded-lg flex items-center justify-center text-white text-xs font-bold flex-shrink-0 shadow-sm ${
                    idx === 0 ? 'bg-gradient-to-br from-amber-400 to-amber-600' : 
                    idx === 1 ? 'bg-gradient-to-br from-slate-300 to-slate-400' : 
                    idx === 2 ? 'bg-gradient-to-br from-orange-400 to-orange-600' : 
                    'bg-gradient-to-br from-slate-600 to-slate-700'
                  }`}>
                    {idx + 1}
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-[13px] font-semibold text-slate-800 truncate">{officer.name}</p>
                    <p className="text-[11px] text-slate-400">{officer.type} • {officer.count} meetings</p>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Day of Week Activity */}
        <div className="bg-white rounded-2xl border border-slate-200/60 shadow-sm p-6 hover:shadow-md transition-shadow duration-300">
          <div className="flex items-center gap-2 mb-5">
            <Zap className="w-5 h-5 text-violet-500" />
            <h3 className="text-[15px] font-bold text-slate-900">Busiest Days</h3>
          </div>
          <div className="flex items-end justify-between gap-2 h-32 px-1">
            {data.dayActivity.map((count: number, idx: number) => {
              const height = (count / data.maxDayActivity) * 100;
              return (
                <div key={idx} className="flex-1 flex flex-col items-center gap-2 group">
                  <div className="w-full bg-slate-100 rounded-t-lg relative overflow-hidden" style={{ height: '100%' }}>
                    <div 
                      className="absolute bottom-0 w-full bg-gradient-to-t from-violet-600 to-violet-400 rounded-t-lg transition-all duration-500 group-hover:from-violet-700 group-hover:to-violet-500" 
                      style={{ height: `${Math.max(height, 4)}%` }} 
                    />
                  </div>
                  <span className="text-[11px] text-slate-400 font-medium">{data.dayNames[idx]}</span>
                </div>
              );
            })}
          </div>
        </div>

        {/* Meeting Types */}
        <div className="bg-white rounded-2xl border border-slate-200/60 shadow-sm p-6 hover:shadow-md transition-shadow duration-300">
          <div className="flex items-center gap-2 mb-5">
            <MapPin className="w-5 h-5 text-teal-500" />
            <h3 className="text-[15px] font-bold text-slate-900">Meeting Types</h3>
          </div>
          {Object.keys(data.meetingTypes).length === 0 ? (
            <div className="flex items-center justify-center h-32 text-slate-400 text-sm">No data available</div>
          ) : (
            <div className="space-y-3">
              {Object.entries(data.meetingTypes).map(([type, count]: [string, any]) => (
                <div key={type} className="flex items-center justify-between p-3 bg-slate-50/80 rounded-xl border border-slate-100">
                  <span className="text-[13px] font-medium text-slate-700">{type}</span>
                  <div className="flex items-center gap-3">
                    <div className="w-16 h-1.5 bg-slate-200 rounded-full overflow-hidden">
                      <div 
                        className="h-full bg-gradient-to-r from-teal-500 to-teal-400 rounded-full transition-all duration-700" 
                        style={{ width: `${(count / data.totalMeetings) * 100}%` }} 
                      />
                    </div>
                    <span className="text-[13px] font-bold text-slate-900 w-5 text-right tabular-nums">{count}</span>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* ─── SEPARATED LOGS SECTION ─── */}
      <div className="bg-white rounded-2xl border border-slate-200/60 shadow-sm overflow-hidden hover:shadow-md transition-shadow duration-300">
        {/* Tab Navigation */}
        <div className="border-b border-slate-100 px-6 pt-5">
          <div className="flex gap-6">
            <button
              onClick={() => setActiveLogTab('reports')}
              className={`pb-3 text-[13px] font-semibold border-b-2 transition-colors flex items-center gap-2 ${
                activeLogTab === 'reports' 
                  ? 'border-slate-900 text-slate-900' 
                  : 'border-transparent text-slate-400 hover:text-slate-600'
              }`}
            >
              <FileText className="w-4 h-4" />
              Report History
              <span className="ml-1 px-1.5 py-0.5 text-[10px] font-bold bg-slate-100 text-slate-600 rounded-full">
                {reportHistory.length}
              </span>
            </button>
            <button
              onClick={() => setActiveLogTab('updates')}
              className={`pb-3 text-[13px] font-semibold border-b-2 transition-colors flex items-center gap-2 ${
                activeLogTab === 'updates' 
                  ? 'border-slate-900 text-slate-900' 
                  : 'border-transparent text-slate-400 hover:text-slate-600'
              }`}
            >
              <Database className="w-4 h-4" />
              Update Logs
              <span className="ml-1 px-1.5 py-0.5 text-[10px] font-bold bg-slate-100 text-slate-600 rounded-full">
                {updateLogs.length}
              </span>
            </button>
          </div>
        </div>

        {/* Tab Content */}
        <div className="min-h-[300px]">
          {activeLogTab === 'reports' ? (
            <ReportHistoryTable data={reportHistory} />
          ) : (
            <UpdateLogsTable data={updateLogs} />
          )}
        </div>
      </div>
    </div>
  );
}